name: Deploy

on:
  push:
    branches: [master]

jobs:
  deploy:
    name: Publish to npm
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@93ea575cb5d8a053eaa0ac8fa3b40d7e05a33cc8 # tag=v3
      - name: Upgrade npm
        run: npm i -g npm@latest
      - name: npm install
        uses: bahmutov/npm-install@cb39a46f27f14697fec763d60fb23ad347e2befa # tag=v1
      - name: Semantic Release
        run: npm run semantic-release -d # dry run for now
        env:
          NPM_TOKEN: ${{ secrets.NPM_TOKEN }}
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

